"""add_watchdog_run

Revision ID: e6e1dae98ee8
Revises: f977c57e5698
Create Date: 2025-12-31 15:53:40.482051

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e6e1dae98ee8'
down_revision = 'f977c57e5698'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watchdog_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ran_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_watchdog_runs'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchdog_runs')
    # ### end Alembic commands ###
