"""Initial schema

Revision ID: f977c57e5698
Revises: 
Create Date: 2025-12-31 15:29:27.339463

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f977c57e5698'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('object_type', sa.String(), nullable=True),
    sa.Column('object_id', sa.String(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_table('conversations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('INDIVIDUAL', 'GROUP', name='conversationtype'), nullable=False),
    sa.Column('business_phone_number_id', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations'))
    )
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('primary_phone_e164', sa.String(), nullable=True),
    sa.Column('primary_email', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers'))
    )
    op.create_table('participants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('phone_e164', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_participants'))
    )
    op.create_table('raw_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('signature_valid', sa.Boolean(), nullable=False),
    sa.Column('correlation_id', sa.String(), nullable=True),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('request_hash', sa.String(), nullable=False),
    sa.Column('headers_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_raw_events'))
    )
    op.create_index(op.f('ix_raw_events_request_hash'), 'raw_events', ['request_hash'], unique=True)
    op.create_table('messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('participant_id', sa.String(), nullable=False),
    sa.Column('direction', sa.Enum('INBOUND', 'OUTBOUND', name='messagedirection'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('message_type', sa.String(), nullable=False),
    sa.Column('text_body', sa.Text(), nullable=True),
    sa.Column('reply_to_message_id', sa.String(), nullable=True),
    sa.Column('raw_event_id', sa.UUID(), nullable=True),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_messages_conversation_id_conversations')),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], name=op.f('fk_messages_participant_id_participants')),
    sa.ForeignKeyConstraint(['raw_event_id'], ['raw_events.id'], name=op.f('fk_messages_raw_event_id_raw_events')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index('ix_messages_conversation_sent_at', 'messages', ['conversation_id', 'sent_at'], unique=False)
    op.create_index('ix_messages_participant_sent_at', 'messages', ['participant_id', 'sent_at'], unique=False)
    op.create_table('participant_aliases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('participant_id', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], name=op.f('fk_participant_aliases_participant_id_participants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_participant_aliases'))
    )
    op.create_table('participant_customer_map',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('participant_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('source', sa.Enum('PHONE_MATCH', 'MANUAL', 'IMPORT', 'INFERRED', name='participantsource'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_participant_customer_map_customer_id_customers')),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], name=op.f('fk_participant_customer_map_participant_id_participants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_participant_customer_map'))
    )
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('doc_type', sa.Enum('INVOICE', 'PDF', 'IMAGE', 'OTHER', name='doctype'), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('storage_key_raw', sa.String(), nullable=False),
    sa.Column('storage_key_sanitized', sa.String(), nullable=True),
    sa.Column('sha256', sa.String(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('extracted_fields_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sensitive_detected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('extraction_status', sa.Enum('PENDING', 'OK', 'FAILED', name='extractionstatus'), nullable=False),
    sa.Column('extraction_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_documents_message_id_messages')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents')
    op.drop_table('participant_customer_map')
    op.drop_table('participant_aliases')
    op.drop_index('ix_messages_participant_sent_at', table_name='messages')
    op.drop_index('ix_messages_conversation_sent_at', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_raw_events_request_hash'), table_name='raw_events')
    op.drop_table('raw_events')
    op.drop_table('participants')
    op.drop_table('customers')
    op.drop_table('conversations')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
